### ISSUE TITLE
 call_api(..., type = 'graph') to graph with no data returns a misleading error

### ISSUE THREAD

**Issue by dfgitn4j** [neo4j-rstats/neo4r#39]
Would hope that the call would recognize that there's no data and return a message indicating that the query returned no data.   For example:
```
x<-"call apoc.meta.graph" %>% call_api(con, type = 'graph')
Your call can't be converted to a graph.
Please switch to type = "row".
```
switching to row will return nothing.

**Comment by ColinFay** [comment]
I've updated the message so it's now : 

``` 
No graph data found.
Either your call can't be converted to a graph 
or there is no data at all matching your call.
Verify your call or try type = "row".
```

Does it sound clearer to you or would you prefer something else?

**Comment by dfgitn4j** [comment]
Good wording - identifies the two causes and proposes an alternative for understanding the underlying root cause.  Thank you.


> I've updated the message so it's now :
> 
> ```
> No graph data found.
> Either your call can't be converted to a graph 
> or there is no data at all matching your call.
> Verify your call or try type = "row".
> ```
> Does it sound clearer to you or would you prefer something else?
