### ISSUE TITLE
could not find function "convert_to"

### ISSUE THREAD

**Issue by wkwong-bison** [neo4j-rstats/neo4r#50]
Trying to follow {neo4r} user guide chapter 6 (convert_to), and getting the following error messages:

   Error in convert_to(., "igraph") : could not find function "convert_to"

   Error in convert_to(., "visNetwork") : could not find function "convert_to"

**Comment by ColinFay** [comment]
Hey, 

Yes, convert_to has been removed in the latest version of the package as it was not working well after all (sorry about that). 

I'm working on it, and we'll bring it back when I will have found a reliable way to approach that functionality. To sum up, it's hard to find something that works for all the use cases, without the user doing some extra work by hand. 

For now, Please do refer to the latest version of the user guide — chapter 6 has a series of methodologies to convert to igraph and visNetwork. Feel free to comment here if you have any question about that section.
