### ISSUE TITLE
Missing relationships from graph query

### ISSUE THREAD

**Issue by BJWiley233** [neo4j-rstats/neo4r#84]
When I run a query in Neo4j I will get for instance 14 node and 22 relationships but running that same query in neo4r gives me same correct number of nodes (14) but only gives me 13 relationships and only 15 relationships when I unnest them.  Any reason for the missing relationships?  Are their limitations on the relationships that won't return to R?

**Comment by davidlrosenblum** [comment]
There is a setting in Neo4j Browser that will connect all the nodes, even if you have not asked for that Relationship in your cypher query.  That is probably what you are seeing.

You will see a Setting Icon (Gear) bottom left.  All the way to the bottom is a Check Box - Connect Result Nodes.  When checked, it will run secondary queries to the one you put in the query box to see if it can find any Relationships to the Labels/Nodes on the screen.



As you can see, I have it unchecked.  My results would match that from a neo4r query.

David

**Comment by BJWiley233** [comment]
Thanks David, learning something new every day about neo4j!
